Repository node-saml/passport-saml, pull requests merged in 2020-11, with the labels that each got.

#486 update version of xml2js to 0.4.23, fixes #479
  package.json
Labels: semver-patch

#428 feat(authorize-request): idp scoping provider
  README.md
  src/passport-saml/saml.ts
  src/passport-saml/types.ts
  test/tests.js
Labels: new-feature, pending-refinement, semver-minor

#412 Always throw error objects instead of strings
  src/passport-saml/saml.ts
  test/tests.js
Labels: 2.0, breaking-change

#488 Allow for use of privateKey instead of privateCert
  README.md
  src/passport-saml/saml-post-signing.ts
  src/passport-saml/saml.ts
  test/saml-post-signing-tests.js
  test/tests.js
Labels: needs-review, semver-minor

#498 normalize line endings before signature validation
  src/passport-saml/saml.ts
  test/test-signatures.js
Labels: semver-patch

#500 support windows line breaks in keys
  src/passport-saml/saml.ts
Labels: semver-patch

#503 fix(typing): multi saml stratey export
  src/passport-saml/index.ts
Labels: semver-patch
