Repository node-saml/passport-saml, pull requests merged in 2021-06, with the labels that each got.

#611 Fix typo OnBefore -> NotBefore
  README.md
Labels: documentation

#605 Rebuild changelog for 3.0.0
  CHANGELOG.md
Labels: documentation

#593 Fix: Conflicting profile properties between profile and attributes
  .gitignore
  src/node-saml/saml.ts
  test/node-saml/tests.spec.ts
Labels: bug, pending-refinement

#595 Limit transforms for signed nodes
  src/node-saml/saml.ts
  test/node-saml/test-signatures.spec.ts
  test/static/signatures/invalid/response.root-signed-transforms.assertion-unsigned.xml
  test/static/signatures/invalid/response.root-unsigned.assertion-signed-transforms.xml
Labels: security
