Repository node-saml/passport-saml, pull requests merged in 2022-06, with the labels that each got.

#699 Adjust .mochars.json
  .mocharc.json
Labels: chore

#696 Update dependencies
  package-lock.json
  package.json
  test/capturedSamlRequests.spec.ts
Labels: dependencies

#701 Add code coverage
  .gitignore
  .nycrc.json
  .prettierignore
  package-lock.json
  package.json
  tsconfig.json
Labels: chore

#706 Add code coverage workflow
  .github/workflows/workflow.yml
Labels: chore

#705 Move to NPM organization
  package.json
Labels: chore

#708 docs: move history note to the bottom and expand it.
  README.md
Labels: documentation

#709 Update badges for scoped package
  README.md
Labels: documentation

#710 Update badges for scoped package
  README.md
Labels: documentation
