Repository node-saml/passport-saml, pull requests merged in 2024-03, with the labels that each got.

#887 Remove unused `AuthorizeOptions` type
  src/types.ts
Labels: chore

#888 Update `package.json` script to mirror `node-saml`
  package.json
Labels: chore

#889 Adjust type enforcement to remove warnings
  .eslintrc.json
  src/types.ts
Labels: chore

#886 Update README to point to `node-saml` documentation
  .prettierrc.json
  README.md
Labels: documentation

#884 Fix README to require correct module name
  README.md
Labels: documentation

#838 StrategyOptionsCallback shouldn't have to pass all SAML options
  src/types.ts
  test/multiSamlStrategy.spec.ts
Labels: bug, needs-review

#893 Update to Node 18
  .github/workflows/workflow.yml
  package.json
Labels: dependencies, semver-major

#894 Update to @node-saml/node-saml v5
  package-lock.json
  package.json
  test/multiSamlStrategy.spec.ts
  test/strategy.spec.ts
Labels: breaking-change, dependencies

#895 Update minor dependencies
  package-lock.json
  package.json
Labels: dependencies, semver-minor

#896 Update major versions of dependencies
  package-lock.json
  package.json
Labels: dependencies, semver-major

#897 Update prettier
  .grenrc.js
  README.md
  docs/xml-signing-example.js
  package-lock.json
  package.json
  src/multiSamlStrategy.ts
  src/strategy.ts
  src/types.ts
  test/multiSamlStrategy.spec.ts
  test/strategy.spec.ts
Labels: dependencies

#898 Update nested dependencies
  package-lock.json
Labels: dependencies
